services:
  - type: web
    name: co-up-tu-tien
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_DIR
        value: /data
    disk:
      name: coup-data
      mountPath: /data
      sizeGB: 1
